services:
  db-main:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: db-main
    env_file:
      - dev.env
    volumes:
      - db-main-data:/var/lib/postgresql/data

volumes:
  db-main-data: