-- CREATE TYPE TYPEARTICLE AS ENUM (
--     'Event Review',
--     'Artist Review',
--     'Venue Review',
--     'Editorial',
--     'Local Politics',
--     'Charity',
--     'Interview',
--     'Announcement',
--     'Feature',
--     'Opinion',
--     'Guide'
-- );