name: Call Reusable 'Build and Publish Docker Image' Action

permissions:
  packages: write
  contents: read

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    uses: bandwidth-gig-guide/ci-workflows/.github/workflows/build-publish.yaml@main
