name: Call Reusable Action

permissions:
  packages: write
  contents: read

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    uses: bandwidth-gig-guide/ci-workflows/.github/workflows/build-publish.yaml@main
    with:
<<<<<<< HEAD
      image_name: db-main
=======
      image_name: database-event
>>>>>>> main
